# based on https://rlesur.gitlab.io/bookdown-gitlab-pages
image: rocker/verse:latest

pages:
  stage: deploy
  script:
    - sudo apt-get update && sudo apt-get -y upgrade --fix-missing  
    - sudo apt-get -y install bzip2
    - Rscript -e "install.packages(c('rmarkdown', 'bookdownplus', 'tinytex', 'webshot'))"
    - Rscript -e "tinytex::install_tinytex(force=TRUE)"
    - Rscript -e "bookdown::render_book('index.Rmd', 'all', output_dir = 'public')"
  artifacts:
    paths:
    - public
  only:
  - main
  
